// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for windows - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxKb4x7MBCPrwk-n-hLhm9PKc9RWhABwA',
    appId: '1:1040203320865:android:2b45485f446cf853d95d60',
    messagingSenderId: '1040203320865',
    projectId: 'posflutter-ce800',
    authDomain: 'posflutter-ce800.firebaseapp.com',
    storageBucket: 'posflutter-ce800.appspot.com',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyB6iDZDL3tO-yAersYbFZ12AMX4xb9zyKY",
    authDomain: "posflutter-ce800.firebaseapp.com",
    projectId: "posflutter-ce800",
    storageBucket: "posflutter-ce800.appspot.com",
    messagingSenderId: "1040203320865",
    appId: "1:1040203320865:web:6b4cc94800c101d7d95d60",
    measurementId: "G-CS11N55Z1E",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiTPXEPA7ArkqCDOAvM2t-eCt5AMSG6kM"',
    appId: '1:1040203320865:android:2b45485f446cf853d95d60',
    messagingSenderId: '1040203320865',
    projectId: 'posflutter-ce800',
    storageBucket: 'posflutter-ce800.appspot.com',
    databaseURL: 'https://posflutter-ce800-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiTPXEPA7ArkqCDOAvM2t-eCt5AMSG6kM"',
    appId: '1:1040203320865:android:2b45485f446cf853d95d60',
    messagingSenderId: '1040203320865',
    projectId: 'posflutter-ce800',
    storageBucket: 'posflutter-ce800.appspot.com',
    databaseURL: 'https://posflutter-ce800-default-rtdb.firebaseio.com',
    iosClientId:
        '77048286492-argcr9ue3lj2avu6qhheek5r57r0u3so.apps.googleusercontent.com',
    iosBundleId: 'com.pos.posflutter',
  );
}
